#:schema node_modules/wrangler/config-schema.json
name = "lintrack"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]
main = "dist/_worker.js/index.js"

# ================== production environment ====================================
[env.prod]
name = "lintrack"

[[env.prod.d1_databases]]
binding = "DB"
database_name = "d1-demo-prod-db"
database_id = "ca0e8d8b-0d5a-4c8d-8aab-d2523e960cb9"

# ================== staging environment =======================================
[env.staging]
name = "lintrack-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "d1-demo-staging-db"
database_id = "21dca118-4ced-4fdb-8b55-e2b61b21cfdc"

# ================== dev environment ===========================================
[env.dev]
name = "lintrack-dev"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "lintrack_dev_db"
database_id = "${lintrack_dev_db}"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
