#:schema node_modules/wrangler/config-schema.json
name = "${{vars.CF_WORKER_NAME_PROD}}"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]
main = "dist/_worker.js/index.js"

# ================== production environment ====================================
[env.prod]
name = "${{vars.CF_WORKER_NAME_PROD}}"

[[env.prod.d1_databases]]
binding = "DB"
database_name = "${{ vars.MAIN_DB }}"
database_id = "${{ vars.MAIN_DB_ID }}"

# ================== staging environment =======================================
[env.staging]
name = "${{vars.CF_WORKER_NAME_STAGING}}"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "${{ vars.STAGING_DB }}"
database_id = "${{ vars.STAGING_DB_ID }}"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true